apiVersion: apps/v1
kind: Deployment
metadata:
  name: argodep
spec:
  selector:
    matchLabels:
      app: default
  replicas: 3
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
      - image: meidal11/argodocker:3
        name: argoapp
        ports:
        - containerPort: 8080
