apiVersion: apps/v1
kind: Deployment
metadata:
  name: argodep
  namespace: default2
spec:
  selector:
    matchLabels:
      app: default
  replicas: 3
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
      - image: ghcr.io/meidal11/devops-interview-argocd:35.0
        name: argoapp
        ports:
        - containerPort: 8080
          #a
