apiVersion: v1
kind: Service
metadata:
  name: argosvc
spec:
  type: NodePort
  selector:
    app: default
  ports:
    - protocol: TCP
      port: 8080
      # targetPort: 9376
      #externalIPs:
          #    - 1.2.4.120
