apiVersion: v1
kind: Service
metadata:
  name: argosvc
spec:
  selector:
    app: default
    #type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  externalIPs:
    - 1.2.4.120
